# Generated by Django 4.0 on 2022-04-09 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='balence',
            new_name='balance',
        ),
    ]
