# Generated by Django 4.0 on 2022-04-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_rename_balence_internship_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='internship',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='internship',
            name='total_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='internship',
            name='total_pay',
            field=models.IntegerField(default=0),
        ),
    ]
