# Generated by Django 4.0 on 2022-04-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_alter_internship_amount_alter_internship_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='complete_status',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='internship',
            name='verify_status',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
